import {
  ACADEMIC_SPLIT,
  EPILOGUE_AT,
  HIDDEN_DISSONANCE,
  HIDDEN_LU,
  WAKE_AT,
} from "./ledger.js";

const sting = { text: "心里那根刺动了一下。", kind: "thought" };

export function epilogueId(state) {
  const rows = [
    ["epi_lu", state.lu],
    ["epi_shen", state.shen],
    ["epi_yu", state.yu],
  ].filter(([, value]) => value >= EPILOGUE_AT);
  if (rows.length === 0) return "epi_default";
  const top = Math.max(...rows.map(([, value]) => value));
  const best = rows.filter(([, value]) => value === top);
  if (best.length > 1) return "epi_tie";
  return best[0][0];
}

export function hiddenReady(state) {
  return state.ngPlus && state.dissonance >= HIDDEN_DISSONANCE && state.lu >= HIDDEN_LU;
}

export const NODES = {
  ng_gate: {
    title: "序章 · 一模之后",
    bg: "schoolgate",
    layer: "real",
    bgm: "june",
    who: "鹿眠",
    face: "distant",
    lines: [
      { text: "校门口的梧桐刚冒芽。白衬衫从门柱那边过去，步子不快。", se: "wind", kind: "thought" },
      { text: "叶子掀起来。等它落回去，人已经不在了。我没看见她的脸。", kind: "thought" },
      { text: "有些人就是这样。先从你眼睛边上走掉。", kind: "thought" },
    ],
    next: "pro_rank",
  },
  pro_rank: {
    title: "序章 · 一模之后",
    bg: "classroom",
    layer: "real",
    bgm: "june",
    cg: "cg_rank",
    fragment: "second",
    who: "郁明",
    face: "bright",
    lines: [
      { text: "一模的榜贴在一楼拐角。纸边被风掀起来，又被谁用图钉按回去。", se: "paper" },
      { text: "全市第二。第一名是郁明。差我三分。" },
      { text: "有人拍我的肩，说第二也够得着秦华。我点头。牙关是咬着的。" },
      { text: "郁明的名字写得很端正。端正得让人没法痛快地恨。" },
      { text: "我在那张纸上看见自己被量过了。短了三寸。短三寸的人还得走路，还得对他笑。" },
    ],
    options: [
      { id: "yu", label: "去找郁明", next: "pro_yu" },
      { id: "leave", label: "先离开榜单", next: "pro_leave" },
    ],
  },
  pro_yu: {
    bg: "classroom",
    layer: "real",
    bgm: "june",
    who: "郁明",
    face: "bright",
    lines: [
      { who: "郁明", face: "bright", voice: true, text: "第二也好啊。秦华的线，我们都够得着。" },
      { text: "他笑起来没有刺。刺长在我身上。" },
      { who: "郁明", face: "soft", voice: true, text: "你要是那两天睡好了，站这儿的说不定是我。一张榜，别看成一辈子。" },
      { text: "他是来卸我的。我听成了另一句：这三分，是你没睡好，该付的。" },
      { text: "我恨这个听法。更恨自己没法告诉他：你这样对我，我反而欠你。" },
      { text: "高一我们就争同一道题。后来争的是谁先低头。他先把台阶递过来。我一步也不想上。" },
    ],
    next: "pro_shen",
  },
  pro_leave: {
    bg: "corridor",
    layer: "real",
    bgm: "june",
    lines: [
      { text: "我把榜单留在身后。走廊里有人喊我的名字。我没应。", se: "step" },
      { text: "一回头，就得把「还行」说给别人听。说出来，那三分就成了我自己承认的尺寸。" },
      { text: "窗外有人在跑。他们的名次写在地上，风一吹就没了。我的贴在墙上。" },
      { text: "郁明大概还站在榜前面，给每个道贺的人让出半步。我走我的。中间是一条空走廊。" },
    ],
    next: "pro_shen",
  },
  pro_shen: {
    bg: "classroom",
    layer: "real",
    bgm: "june",
    who: "沈知夏",
    face: "shy",
    pose: "turn",
    lines: [
      { text: "沈知夏把一张折好的纸放在我桌上。折痕压得很死。", se: "paper" },
      { text: "她不看我。右眼角那颗痣，我看了三年。看的时候总假装在看黑板。" },
      { text: "同桌三年，卷子传过，多余的话没有。名次一高，话就更说不出口。" },
      { text: "她把纸推过来的手指很稳。她知道我只会盯着榜。" },
      { who: "沈知夏", face: "quiet", pose: "turn", voice: true, text: "你先看着。不看也行。我放这儿。" },
    ],
    options: [
      { id: "open", label: "现在拆开", next: "pro_open" },
      { id: "pocket", label: "放进口袋", next: "pro_pocket" },
    ],
  },
  pro_open: {
    bg: "classroom",
    layer: "real",
    bgm: "june",
    who: "沈知夏",
    face: "quiet",
    lines: [
      { text: "纸上只有一句：别只看着名次。字很小，能看出停过笔。" },
      { text: "没有称呼，没有落款。落款会把这件事变成一封要回的信。她不逼我回。" },
      { who: "沈知夏", face: "shy", pose: "turn", voice: true, text: "你要是想假装没看见，也行。我又不是来收账的。" },
      { text: "退路是她先递过来的。她比我清楚我会逃。" },
      { text: "我抬眼的时候，她已经在看窗外。痣还在。我想说一句跟名次无关的话，嘴张了张，只吐出一口气。" },
      { who: "沈知夏", face: "hurt", voice: true, text: "行了。你别用那种看试卷的眼神看我。" },
    ],
    next: "pro_pei",
  },
  pro_pocket: {
    bg: "classroom",
    layer: "real",
    bgm: "june",
    who: "沈知夏",
    face: "hurt",
    lines: [
      { text: "我把纸按进口袋。按得很死，像怕它自己叫出声。", se: "paper" },
      { text: "她的目光在我肩上停了一下，就移开了。手收回去，还装作本来就没伸。" },
      { who: "沈知夏", face: "hurt", pose: "turn", voice: true, text: "口袋里也行。别揉烂就行。" },
      { text: "我点头。她转身，裙摆碰了一下桌角。", se: "step" },
      { text: "三年的注视，被我收成口袋里的一张纸。她还来嘱咐我别揉烂。" },
    ],
    next: "pro_pei",
  },
  pro_pei: {
    bg: "corridor",
    layer: "real",
    bgm: "june",
    who: "裴望",
    face: "stern",
    lines: [
      { who: "裴望", face: "stern", voice: true, text: "学校可以订酒店。考点旁边，眠夏。你那个失眠，我知道。" },
      { text: "他说话不绕。羊数到三百还在，他知道。高二我在他办公室趴到天亮，卷子上全是口水。" },
      { text: "父母会把这个收进家里的脸。他把它收进一张床。床是好的。好的东西压在头上，也喘不上气。" },
      { who: "裴望", face: "soft", voice: true, text: "不是开小灶。是一张床。你要觉得这是恩典，那是你自己想多了。" },
      { text: "他这么说，我就更欠他。" },
    ],
    options: [
      { id: "pride", label: "不想被单独对待", next: "pro_pride" },
      { id: "money", label: "家里不该花这笔钱", next: "pro_money" },
    ],
  },
  pro_pride: {
    bg: "corridor",
    layer: "real",
    bgm: "june",
    who: "裴望",
    face: "stern",
    lines: [
      { text: "我说不用。被单独留下一张床，我会更睡不着。同宿舍的人会问。" },
      { text: "问的不是酒店。是我为什么值得被从九十厘米的铁架上拎出去。" },
      { who: "裴望", face: "soft", voice: true, text: "随你。考场见。别跟自己过不去。过不去的那天，题不会等你。" },
      { text: "他走了。我站了一会儿。很小的一个回合，赢完手心是空的。", se: "step" },
    ],
    next: "ch1_dorm",
  },
  pro_money: {
    bg: "corridor",
    layer: "real",
    bgm: "june",
    who: "裴望",
    face: "stern",
    lines: [
      { text: "我说家里的钱不该花在一张床上。母亲这个月已经把肉买少了。" },
      { text: "真的是肉。假的是我用肉挡住他的眼睛。我怕的不是钱，是被安排。" },
      { who: "裴望", face: "soft", voice: true, text: "嘴硬。考场见。钱的事你不用拿来堵我。我又不是来收你学费的。" },
      { text: "他看穿了，不戳破。我宁愿他骂我矫情。" },
    ],
    next: "ch1_dorm",
  },
  ch1_dorm: {
    title: "第一章 · 考点之夜",
    bg: "dorm",
    layer: "real",
    bgm: "bed",
    cg: "cg_bed",
    fragment: "bed",
    lines: [
      { text: "床是铁架的，九十厘米宽。翻个身，整栋楼都听得见。", se: "creak" },
      { text: "抬腰，挪肩，脚踝压住床沿，停三秒，再把重量交回去。六步。人也不睡。" },
      { text: "上铺的鼾声一阵一阵，像有人在很近的地方锯木头。", se: "snore" },
      { text: "空调正对着脸。羊数到三百七十四。", se: "ac" },
      { text: "母亲的话从羊群里挤进来：这次要是考不好，我们家的脸往哪搁。羊全散了。" },
      { text: "她只说过一次。一次就够我背到现在。背得比课文熟。" },
      { text: "凌晨三点十七分。手机亮着。想打给老裴，又觉得这一打，就把下午那点骨气交回去。", se: "phone" },
    ],
    options: [
      { id: "down", label: "把手机扣过去", next: "ch1_down" },
      { id: "call", label: "拨给老裴", next: "ch1_call" },
    ],
  },
  ch1_down: {
    bg: "dorm",
    layer: "real",
    bgm: "bed",
    lines: [
      { text: "太晚了。明天是第一场语文。屏幕暗下去。", se: "click" },
      { text: "我松了口气，又恨这口气。没求人，并不能当睡觉的理由。床还是九十厘米。" },
      { text: "手机压在枕头底下。还听得见它不响。" },
    ],
    next: "ch1_exam",
  },
  ch1_call: {
    bg: "dorm",
    layer: "real",
    bgm: "bed",
    who: "裴望",
    face: "soft",
    lines: [
      { text: "电话响了两声他就接了。", se: "phone" },
      { who: "裴望", face: "soft", voice: true, text: "喂？黍琊？这会儿订不到了。你先把手机放下，把眼睛闭上。闭不上，也别睁着跟天花板打架。" },
      { text: "我闭上了。眼睛还是干的。他的声音稳，低，没有责备。" },
      { text: "我在黑暗里说了声对不起。他说不用。" },
      { who: "裴望", face: "soft", voice: true, text: "语文先把字写端正。端正不是给判卷的人看的。是给你自己一个能抓住的东西。" },
    ],
    next: "ch1_exam",
  },
  ch1_exam: {
    bg: "exam",
    layer: "real",
    bgm: "exam",
    lines: [
      { text: "六月七日，七点四十分。座位是木头的。木头比铁架安静。", se: "pen" },
      { text: "字在纸上发虚。第一题我读了三遍，三遍都像别人的卷子。" },
      { text: "旁边的人已经在写了。笔尖很密。" },
      { text: "老裴说的端正，需要一个睡过觉的手。手在。觉不在。" },
    ],
    options: [
      { id: "read", label: "把题再读一遍", next: "ch1_read" },
      { id: "clock", label: "看了一眼时钟", next: "ch1_clock" },
    ],
  },
  ch1_read: {
    bg: "exam",
    layer: "real",
    bgm: "exam",
    lines: [
      { text: "第四遍，句子终于站住。我写下去。字还是飘，可飘着的字也是字。", se: "pen" },
      { text: "我不再跟第一题吵架。能写的先写。写的时候有一瞬间，考场变回考场，不是审判庭。" },
      { text: "那一瞬间很短。短完之后，我还是写完了。写完不等于写好。写完只是我没有在中途把笔放下。" },
    ],
    next: "ch1_score",
  },
  ch1_clock: {
    bg: "exam",
    layer: "real",
    bgm: "exam",
    lines: [
      { text: "时针走得很响。我听钟，不听题。钟是公平的，公平得残忍，它不因为你没睡就走慢一点。", se: "clock" },
      { text: "我看了太久。等我低头，答题卡上的空格比刚才更白。" },
      { text: "白不是失败。白是我自己把时间交给了一个不会回答我的东西。" },
    ],
    next: "ch1_score",
  },
  ch1_score: {
    bg: "home",
    layer: "real",
    bgm: "june",
    who: "裴望",
    face: "soft",
    lines: [
      { text: "出分那天，家里没有开灯。黄昏从窗帘缝里进来，把桌子切成一条亮、一条暗。" },
      { text: "母亲把成绩单折好。折一下，再折一下。折痕深过上面的数字。", se: "paper" },
      { text: "她没说话。我准备好了被责问。责问没有来。" },
      { text: "对不起到了嘴边，又咽回去。她不知道手该放在哪里。" },
      { text: "老裴来了。他没说还有机会，也没说复读。" },
      { who: "裴望", face: "soft", voice: true, text: "先喝水。" },
      { text: "水是温的。我喝了。他坐在对面，看自己的手，不看我。", se: "cup" },
      { text: "郁明的消息亮了一下。我没点开。沈知夏的信在门口，我让它待着。" },
      { text: "六月九日凌晨。我躺回那张让我落榜的床。铁架响了一声。我睡着了。", se: "creak" },
    ],
    next: "ch2_white",
  },
  ch2_white: {
    title: "第二章 · 白光的选项",
    bg: "white",
    layer: "limen",
    bgm: "white",
    cg: "cg_white",
    fragment: "white",
    lines: [
      { text: "光没有来处。像候考室的灯。" },
      { text: "成绩单、折痕、没拆的信，都停在光的外面。" },
      { text: "有个人影站在光的另一头。白衬衫。我看不清她的脸。" },
      { text: "她不催我。催我的是我自己。再来一次，会不会就不再短那三寸。" },
    ],
    options(state) {
      const options = [
        { id: "accept", label: "认命，接受成绩单", next: "end_a" },
        { id: "again", label: "再来一次，开启新的人生", next: "ch3_hotel" },
      ];
      if (state.ngPlus && !state.flags.ngSpoke) {
        options.push({
          id: "seen",
          label: "你好像在哪里见过她",
          next: "ch2_ng",
          set: { ngSpoke: true },
        });
      }
      return options;
    },
  },
  ch2_ng: {
    bg: "white",
    layer: "limen",
    bgm: "white",
    lines: [
      { text: "那人影侧了一下头。白衬衫。校门口的那一下，忽然对上了。" },
      { text: "不是梦替我补完的脸。是我第一次没看清、后来又在前台玻璃里站住的那个人。" },
      { text: "她也不解释。解释会把重逢写成剧情。她只是让我知道，这光里不只有我一个人记得校门口的风。" },
      { text: "光没有回答。选项还在。还在，是因为记得她，并不能替我决定要不要重来。" },
    ],
    next: "ch2_white",
  },
  end_a: {
    bg: "rain",
    layer: "real",
    bgm: "rain",
    ending: "A",
    lines: [
      { text: "我接过成绩单。雨从楼道尽头淌进来，把鞋面打湿。", se: "rain" },
      { text: "母亲后来把那张纸收进抽屉最底下。我们都不再翻。" },
      { text: "我上了一所普通的一本。床还是窄，铁架不那么响。觉是慢慢回来的。" },
      { text: "郁明去了秦华。别人告诉我的。我说了声挺好。这两个字，我练过，练到没有破音。" },
      { text: "沈知夏的信我到底拆开了。别只看着名次。我回：我看见了。她回：够了。" },
      { text: "多年以后我路过那所高中。雨还在。我在校门口站了一会儿，没有进去找那张榜。" },
      { text: "那一晚的光，我没有再走进去。" },
      { text: "失败没有把我变成一个深刻的人。它把我留在雨里。雨里的人还是要买菜，还是要睡觉。睡觉这件事，后来被我做成了。" },
    ],
  },
  ch3_hotel: {
    title: "第三章 · 重来之日",
    bg: "lobby",
    layer: "dream",
    bgm: "cradle",
    who: "裴望",
    face: "professor",
    lines: [
      { text: "白光一收，日历翻回六月五日。空气里有一种刚铺好床单的气味，干净得过分。" },
      { text: "我还记得落榜。记得的方式却变轻了，像记得别人的一场雨。" },
      { who: "裴望", face: "professor", voice: true, text: "学校把酒店订了。眠夏，八楼。你好好睡。这次别跟自己较劲。" },
      { text: "他的声音还是老裴，衣服却不像高中老师。我没问为什么。在这个轻飘飘的六月五日里，不问是很容易的。" },
      { text: "容易本身让我不安。真正的日子没有这么体贴。体贴得整齐的世界，像一张已经填好的表。" },
    ],
    next: "ch3_sleep",
  },
  ch3_sleep: {
    bg: "guest",
    layer: "dream",
    bgm: "cradle",
    lines: [
      { text: "我没记得自己答应过。床很软。软到翻身不需要拆成六步。" },
      { text: "我一觉睡到自然醒。醒来的时候窗外是亮的，亮得没有重量。梦里的床没有铁。没有铁的床不提醒你，你是一个会弄出声音的人。" },
      { text: "我躺着，试着恨这张床。恨不起来。身体太感谢它了。感谢是一种收买。被收买的人会开始相信，上次失败只是因为床不够软。" },
      { text: "如果失败能用一张床买掉，那失败就太便宜了。可我还是又睡了十分钟。十分钟里，我没有数羊。" },
    ],
    next: "ch3_out",
  },
  ch3_out: {
    bg: "examout",
    layer: "dream",
    bgm: "cradle",
    cg: "cg_exam_ok",
    lines: [
      { text: "六月七日。笔是稳的。题是清楚的。清楚得像有人提前把雾擦掉了。", se: "pen" },
      { text: "我写完的时候还有空看了一眼自己的字。字是端正的。端正来得毫不费力。毫不费力的端正，我不信任。" },
      { text: "出考场时，太阳白得不真实。白不像晒，像一层罩在所有人头上的光，谁也不眯眼。" },
      { text: "有人说今年简单。有人笑。笑是真的。我跟着笑了一下，笑完舌头是麻的。" },
    ],
    next: "d1",
  },
  d1: {
    bg: "lobby",
    layer: "dream",
    bgm: "cradle",
    cg: "cg_desk",
    who: "鹿眠",
    face: "knowing",
    lines: [
      { text: "前台的玻璃后面站着一个女孩。她看着我，没有把目光挪去别处。" },
      { text: "白衬衫。校门口没看清的那张脸，好像在这块玻璃里停住了。" },
      { who: "鹿眠", face: "knowing", voice: true, text: "考完了？" },
      { text: "两个字。像问住客要不要续房。我习惯的问法是：能不能上线。" },
    ],
    options: [
      {
        id: "ask",
        label: "回头看前台那个女孩",
        next: "crack_cal",
        fx: { d: 6, lu: 10 },
        say: { who: "鹿眠", face: "soft", voice: true, text: "你看起来，像是终于睡过一觉的人。别急着把这觉当成你应得的。" },
        thought: sting,
      },
      { id: "skip", label: "直接离开", next: "crack_cal", thought: "我走出旋转门。玻璃上有她的影子，我没回头。不回头的理由很老：我还没准备好被一个陌生人看穿我刚刚睡过。" },
    ],
  },
  crack_cal: {
    bg: "calendar",
    layer: "dream",
    bgm: "crack",
    onEnter: { d: 4 },
    fragment: "june9",
    lines: [
      { text: "大堂的日历停在六月九日。我按了一下，纸页不动。不动的不是纸，是这个世界同意停在出分前后的那一天。" },
      { text: "六月九日。我落榜的那天，也是我终于睡着的那天。梦把这一天订在墙上，像订一间不会退房的房。" },
      { text: "前台的人走过，看也不看。没有人觉得这有什么奇怪。奇怪的只有我。一个人觉得奇怪的时候，他要么疯了，要么还没完全被这张床收买。" },
      { text: "我又按了一下。指尖是凉的。凉意很短，短得像一句不被允许的话。" },
    ],
    next: "d2",
  },
  d2: {
    bg: "gate",
    layer: "dream",
    bgm: "qinhua",
    cg: "cg_gate",
    lines: [
      { text: "录取来得太顺。顺得像一份早就写好的评语，只等我把名字填进去。秦华的校门立在眼前，匾额像是新的。" },
      { text: "新不是光鲜。新是没有雨打过，没有手摸过，没有哪一届学生在下面哭过或者笑过。" },
      { text: "我盯着那几个字。笔画好像多了一笔，又好像没有。多的那一笔一闪，就躲进正字里。正字看着我，像在问：你不是一直想站在这里吗。" },
      { text: "我想。我想了整整三年。真站到这里，脚底板发虚。虚不是不配。虚是这扇门不记得我交过的那些夜里。" },
    ],
    options: [
      {
        id: "ask",
        label: "总觉得校名哪里不对，再看一眼",
        next: "d2_plaque",
        fx: { d: 6 },
        thought: sting,
      },
      { id: "skip", label: "拍照，发一条朋友圈", next: "daily1", thought: "照片里的校门很完美。评论区全是恭喜。恭喜叠在一起，像一种温和的淹没。我把手机扣上，扣上的声音比恭喜诚实。" },
    ],
  },
  d2_plaque: {
    bg: "plaque",
    layer: "dream",
    bgm: "crack",
    fragment: "plaque",
    lines: [
      { text: "我走近。匾额上的字忽然正了。多出来的那一笔却还在眼睛里，像看完灯之后的那块黑斑。", kind: "glitch" },
      { text: "黑斑不在石头上。在我眼睛里。梦允许石头立刻改口，不允许我立刻忘记自己看见过。" },
      { text: "我站在校名下面，第一次觉得成功有一种气味：新漆，还有一点尘。尘是我自己带来的。门不承认尘。" },
    ],
    next: "daily1",
  },
  daily1: {
    bg: "gate",
    layer: "dream",
    bgm: "qinhua",
    lines: [
      { text: "入学第一周，下午空出一截。空得不自然。高中的下午从来不会空，空了也要被卷子填上。" },
      { text: "我站在校门里侧，不知道该把这段时间交给谁。交给谁，就是承认我在这座太顺的学校里，还是会想某一个人。" },
      { text: "想郁明，是想那个把台阶递过来的人，我想知道他在这里还笑不笑。想沈知夏，是想那颗不该被改掉的痣。想前台那个女孩，是想一块还没有把我认成成功者的玻璃。" },
    ],
    options: [
      { id: "lu", label: "去前台找鹿眠", next: "acad1", fx: { lu: 5 }, say: { who: "鹿眠", face: "soft", text: "你又来。咖啡是热的。你却总看着电梯。电梯不会因为你看起来去，就停在你要的那一层。" } },
      { id: "shen", label: "去找沈知夏", next: "acad1", fx: { shen: 5 }, say: { who: "沈知夏", face: "shy", pose: "turn", text: "学姐？……你这么叫我，我会不习惯。不习惯不是生气。是你把我从那张纸条里请出来，又放进一个更安全的称呼里。" } },
      { id: "yu", label: "去找郁明", next: "acad1", fx: { yu: 5 }, say: { who: "郁明", face: "rival", text: "来得正好。这道题我跟你争。你要是让我，我反而瞧不起你。" } },
    ],
  },
  acad1: {
    bg: "library",
    layer: "dream",
    bgm: "lamp",
    lines: [
      { text: "社团招新和图书馆的灯撞在同一个下午。一边是人声，一边是灯。人声要我成为某个圈子里的人。灯什么也不要，只是亮着。", se: "page" },
      { text: "我站在路口，觉得这是一个很小的成败。小到不配被叫做选择。可小的选择会积成一张表，表的最后一格写着你是谁。" },
    ],
    options: [
      { id: "a", label: "泡进图书馆", next: "d3", fx: { academic: 10 }, thought: "灯一直亮到闭馆。名字在借书条上写得很直。直是一种舒服，也是一种旧病：我又开始用留下的痕迹证明自己在场。" },
      { id: "b", label: "去社团看看", next: "d3", fx: { academic: -10 }, thought: "我在人群里站了一小时。有人递来报名表，我拿着，没写。什么也没留下。没留下的一小时，竟然让我松了松肩膀。" },
    ],
  },
  d3: {
    bg: "cafeteria",
    layer: "dream",
    bgm: "pork",
    lines: [
      { text: "食堂。红烧肉。第四天，同一道菜。酱色一样，连盘子边沾上的位置都一样。", se: "cup" },
      { text: "家里把肉买少的那些月里，一旦买了，就会做得很慢。整间屋子都是这个味道。" },
      { text: "排队的人没有谁皱眉。他们不觉得自己在重复。" },
      { text: "我不皱眉，就能继续做这个世界的好学生。皱眉，就是还记得家里那口锅。" },
    ],
    options: [
      { id: "ask", label: "问阿姨：今天是不是又是红烧肉", next: "d3_plate", fx: { d: 10 } },
      { id: "skip", label: "换个窗口，眼不见为净", next: "crack_id", thought: "我换了窗口。味道还是从背后飘过来。不见，不等于它同意离开。它像母亲的那句话，换一条路，也会跟来。" },
    ],
  },
  d3_plate: {
    bg: "pork",
    layer: "dream",
    bgm: "crack",
    fragment: "pork",
    who: "阿姨",
    face: "pause",
    lines: [
      { who: "阿姨", face: "pause", voice: true, text: "同学，食堂哪来的红烧肉？你看清楚。今天是青菜。" },
      { text: "我低头。盘子里分明是。油在灯下闪。" },
      { text: "她没有恶意。她是真心觉得我在无中生有。", kind: "glitch" },
      { text: "广播里的歌走了一拍。我抓紧盘子。盘子是热的。", se: "static" },
    ],
    next: "crack_id",
  },
  crack_id: {
    bg: "classroom",
    layer: "dream",
    bgm: "crack",
    onEnter: { d: 4 },
    fragment: "status",
    lines: [
      { text: "导师点名，问我应届还是复读。这个问题像一根细针。我答了。答完，他已经在叫下一个人。" },
      { text: "全班没有人记得我的答案。连我自己都不确定刚才说的是哪一个。应届是这张床给我的身份。复读是我身体还记得的铁架。" },
      { text: "两种身份都想要我。要我的方式一样客气。客气的世界不跟你吵，它只是不把你的话留下。" },
      { text: "我坐下去，笔记本摊开，字写得很直。直的字不能证明我是谁。它只能证明我还想被证明。" },
    ],
    next: "d4",
  },
  d4: {
    bg: "dorm",
    layer: "dream",
    bgm: "cradle",
    who: "郁明",
    face: "blank",
    pose: "sit",
    lines: [
      { text: "郁明坐在床沿上，膝上搁着一小块蛋糕。蜡烛是后来插上去的，歪着。" },
      { who: "郁明", face: "blank", pose: "sit", voice: true, text: "今天我生日。大概。你来了就行，日期这种东西，过了就过了。" },
      { text: "蛋糕上的日期被奶油糊住了。糊住的地方我很想刮开。刮开如果什么都没有，那他这个人就被梦擦掉了一块。" },
      { text: "高中时他什么都记得。记得我哪道题错在运算，记得我失眠却不把它当笑话说出去。现在他笑着，眼睛却对不准焦点。对不准的笑，比不笑更让我发冷。" },
      { text: "我忽然恨这个梦。它留给他一个生日，却不留给他生日是哪一天。它要一个好对手，不要一个具体的人。" },
    ],
    options: [
      {
        id: "ask",
        label: "追问：你生日到底是哪天",
        next: "acad2",
        fx: { d: 6, yu: 6 },
        say: { who: "郁明", face: "sting", pose: "sit", text: "我……想不起来。奇怪。我以前记得很清楚。清楚到能拿来气你。现在气不起来，空得很。" },
        thought: sting,
      },
      { id: "skip", label: "打趣带过", next: "acad2", thought: "我们碰了杯。他笑着，眼睛是空的。我跟着笑。两个空的人碰杯，声音还是清的。清脆不能当生日。" },
    ],
  },
  acad2: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    who: "裴望",
    face: "professor",
    lines: [
      { who: "裴望", face: "professor", voice: true, text: "我这里有个课题。你要不要接下来。接下来，后面的路会干净很多。" },
      { text: "干净。他又用了这种词。高中时他让我把字写端正，是给我一个能抓住的东西。现在的干净，像要把我身上那些夜里、折痕、没拆的信都洗掉。" },
      { text: "我看着他。他还是会给我倒水的那个人吗。白大褂的影子落在实验台上，把杯子的位置挡住了。" },
    ],
    options: [
      { id: "a", label: "接下来", next: "d5", fx: { academic: 15 }, thought: "课题本上写下我的名字。笔顺很熟，像老裴批改作文的那支。熟让我安心，也让我害怕：我又一次用顺从来换一张床。" },
      { id: "b", label: "缓一缓", next: "d5", fx: { academic: -5 }, thought: "我说再看看。他点头，好像早知我会这样。早知是一种爱，也是一种把人写进括号里的习惯。" },
    ],
  },
  d5: {
    bg: "library",
    layer: "dream",
    bgm: "lamp",
    who: "沈知夏",
    face: "quiet",
    lines: [
      { text: "沈知夏站在书架尽头。在这里她是学姐。声音还是那个声音，慢，停得准。" },
      { text: "右眼角干干净净。干净得像一张被改过的照片，改的人技术很好，好到旁人会夸她好看。" },
      { text: "我好看了三年的不是这张干净的脸。是那颗让我不敢看太久的痣。梦把她变成一个更适合出现在成功故事里的学姐。成功故事不需要一颗会被人记住三年的痣。" },
      { text: "她对我笑。笑是善意的。善意如果建立在一个被删掉的细节上，我就不知道该接住还是该把它还回去。" },
    ],
    options: [
      {
        id: "ask",
        label: "问：你右眼角是不是有颗痣",
        next: "daily2",
        fx: { d: 10, shen: 10 },
        fragment: "mole",
        say: { who: "沈知夏", face: "pause", voice: true, text: "痣？我没有吧。你记错人了。记错也没关系，学弟。" },
        thought: { text: "她的笑停了零点三秒。零点三秒里，那个会把退路先递给我的人好像回来了，又被学姐这个词盖住。", kind: "glitch" },
      },
      { id: "skip", label: "归给光线", next: "daily2", thought: "我把那一下归给日光灯。书页恢复了平整。平整的书页好读。好读的东西，常常是被删过的。" },
    ],
  },
  daily2: {
    bg: "library",
    layer: "dream",
    bgm: "lamp",
    lines: [
      { text: "闭馆铃响了。灯一盏一盏灭，灭的顺序很规矩。", se: "chime" },
      { text: "还可以再陪一个人走一段。走一段不是恋爱。是我还想确认，这个太顺的夜里，有没有一个不会被改口的人。" },
      { text: "鹿眠站在规则外面，她连这座学校的学生都不是。沈知夏在规则里面，被叫学姐。郁明在宿舍里，生日是一块糊住的奶油。我要走向谁，就是选择我还肯把哪一种疼带在身上。" },
    ],
    options: [
      { id: "lu", label: "绕去酒店前台", next: "d6", fx: { lu: 5 }, say: { who: "鹿眠", face: "knowing", text: "这么晚。电梯还是不停八楼。你来找我，不如说你来确认它还是不停。" } },
      { id: "shen", label: "送沈知夏到路口", next: "d6", fx: { shen: 5 }, say: { who: "沈知夏", face: "smile", text: "你走路的样子，和那年一样。看着地，像地上写着分数。我还是希望你偶尔看看旁边。" } },
      { id: "yu", label: "回宿舍找郁明", next: "d6", fx: { yu: 5 }, say: { who: "郁明", face: "bright", text: "你回来了。灯我给你留着。留灯容易，记住自己是谁难一点。你别学我。" } },
    ],
  },
  d6: {
    bg: "guest",
    layer: "dream",
    bgm: "cradle",
    who: "黍母",
    face: "expect",
    lines: [
      { text: "母亲来电话。她的声音轻得不像她。轻得像怕吓着一个已经成功的儿子。" },
      { text: "真实的她不是这样轻的。真实的她会把成绩单折出印。真实的她说过，我们家的脸往哪搁。那句话伤人。伤人的声音至少有重量。" },
      { text: "现在这只听筒里的母亲，重量被抽走了。抽走之后只剩下好。好得我不敢认。" },
    ],
    options: [
      {
        id: "ask",
        label: "问：妈，你现在在做什么",
        next: "acad3",
        fx: { d: 6 },
        fragment: "mother",
        say: { who: "黍母", face: "gentle", voice: true, text: "我在做饭呀。你想吃什么，妈都给你做。红烧肉也行，什么都行。你不用再替家里省。" },
        thought: sting,
      },
      { id: "skip", label: "报喜，不报忧", next: "acad3", thought: "我说我很好。她说她知道。电话像一句录好的台词。录好的爱比责骂更难挂断，因为你不好意思对一份礼物说这不是你。" },
    ],
  },
  acad3: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    lines: [
      { text: "实验做到后半夜。数据还差最后一组。差的那一组像一分，差一分的人会以为再熬一会儿就能补上。" },
      { text: "实验室的灯比宿舍白。白灯下面，人会变得很愿意相信自己正在成为该成为的人。" },
      { text: "我看着曲线。曲线还没闭合。闭合是一种成功的形状。我已经开始喜欢这个形状，喜欢到忘记自己为什么坐在这里。" },
    ],
    options: [
      { id: "a", label: "通宵做完", next: "d7", fx: { academic: 10 }, thought: "天亮的时候，曲线终于闭合。我没有困。不困不是休息够了，是这具身体被成功借用了，它暂时不向我要觉。" },
      { id: "b", label: "回去睡", next: "d7", thought: "我躺下。梦里的床太软，软得像没有重量。没有重量的睡眠，醒过来也不觉得自己活过那几个小时。" },
    ],
  },
  d7: {
    bg: "no301",
    layer: "dream",
    bgm: "crack",
    who: "鹿眠",
    face: "serious",
    lines: [
      { text: "房卡上印着 301。我在八楼走了一圈。302 在，303 在，中间那一段墙是平的。没有这个门。", se: "card" },
      { text: "卡却每天都被我握在手里。握一件不存在的钥匙，久了，手会以为门是自己的错。" },
      { text: "鹿眠如果在，她会怎么说。她不是来夸我睡得好的人。她看着电梯的样子，像看着一个她早已知道的故障。" },
    ],
    options: [
      {
        id: "ask",
        label: "回前台，找鹿眠问清楚",
        next: "crack_301",
        fx: { d: 10, lu: 10 },
        say: { who: "鹿眠", face: "serious", text: "你终于来问了。八楼没有 301。你的卡却每天都在刷它。刷不开的时候，你有没有觉得是自己不够努力。" },
        thought: { text: "卡是凉的。凉得不像塑料。她没有安慰我。不安慰，是她肯把我当一个还醒着的人。", kind: "glitch" },
      },
      { id: "skip", label: "换一间，别再想", next: "crack_301", thought: "我换了朝南的一间。阳光很好。夜里还是会走到走廊尽头，用手去摸那面平墙。平墙不回答。不回答也被我摸成了一种关系。" },
    ],
  },
  crack_301: {
    bg: "no301",
    layer: "dream",
    bgm: "crack",
    onEnter: { d: 4 },
    fragment: "room301",
    lines: [
      { text: "电梯的楼层灯跳过了八。没有人按。数字从七直接到九，跳得理直气壮。" },
      { text: "理直气壮的遗漏最可怕。它不道歉，所以你也无法原谅。你只能怀疑自己看错了楼层。" },
      { text: "我在电梯里站着，看那颗跳过去的灯。看久了，几乎要替它圆场：也许八楼在检修。也许我的卡写错了。圆场是我的老本行。榜上差三分的时候，我就在替世界圆场。" },
    ],
    next: "acad4",
  },
  acad4: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    who: "沈知夏",
    face: "quiet",
    lines: [
      { text: "学术会议和沈知夏的消息来自同一个傍晚。一个要我去被看见，一个只是问我在不在。" },
      { text: "被看见是成功的货币。在不在，是另一回事。一个人可以在领奖台上被看见，同时对某个等他的人来说并不在。" },
      { who: "沈知夏", face: "quiet", voice: true, text: "你要是忙，就去。我不是来跟你的前途抢时间的。" },
      { text: "她又把退路递给我。我听得出这不是客气。这是她怕自己变成我成功路上的一个障碍，所以先把自己放低。放低的人，最不该被丢下，也最容易被丢下。" },
    ],
    options: [
      { id: "a", label: "去参加会议", next: "d8", fx: { academic: 10 }, thought: "会场的灯很冷。我的名字被念到，掌声整齐。整齐的时候我想起她说的那句「就去」。我去了。她的低，被我收成了一场出席。" },
      {
        id: "b",
        label: "留下来陪沈知夏",
        next: "d8",
        fx: { academic: -10, shen: 10 },
        say: { who: "沈知夏", face: "smile", voice: true, text: "你居然没去。那我请你喝热的。别用抱歉的脸喝。你要是抱歉，这杯就成了你施舍给我的缺席。" },
      },
    ],
  },
  d8: {
    bg: "award",
    layer: "dream",
    bgm: "applause",
    who: "裴望",
    face: "professor",
    lines: [
      { who: "裴望", face: "professor", voice: true, text: "年度最年轻学者。这个词我替你担着。你只要站好。" },
      { text: "颁奖词下面，年份是去年。去年的我还在铁架床上数羊。掌声很齐。没有人看那一行小字。" },
      { text: "我站在他写好的词里面。词很漂亮。漂亮的词不需要一个真实的去年。真实的去年会让这台子塌下去。" },
      { text: "我看向台下。脸都在。又好像只要我不追问，脸就可以一直在。" },
    ],
    options: [
      {
        id: "ask",
        label: "会后找裴教授核对年份",
        next: "daily3",
        fx: { d: 6 },
        fragment: "lastyear",
        say: { who: "裴望", face: "overlap", text: "年份？印刷的问题。你去准备下一场。下一场才是你的。过去那种东西，留着没用。" },
        thought: sting,
      },
      { id: "skip", label: "和大家一起鼓掌", next: "daily3", thought: "我跟着鼓掌。手心是热的，像别人的。别人的手也会累。我不知道累的是谁。" },
    ],
  },
  daily3: {
    bg: "roof",
    layer: "dream",
    bgm: "cradle",
    lines: [
      { text: "颁奖结束，天台的风是冷的。冷是今晚第一个不像奖状的东西。", se: "wind" },
      { text: "还可以把今晚交给一个人。交给谁，谁就要看见我手里那个沉的杯子，和我还在抖的手。" },
      { text: "我不想被祝贺。祝贺是今天已经太多的东西。我想被问一句不漂亮的话。" },
    ],
    options: [
      { id: "lu", label: "给鹿眠打电话", next: "acad5", fx: { lu: 5 }, say: { who: "鹿眠", face: "whisper", text: "别在梦里站太高。风大。你要是摔了，下面那些鼓掌的人不会接你，他们的手是齐的，不是热的。" } },
      { id: "shen", label: "把沈知夏叫上来", next: "acad5", fx: { shen: 5 }, say: { who: "沈知夏", face: "look", pose: "turn", text: "奖杯沉吗。你的手在抖。抖就抖，别笑成那样。那样的笑我在榜下面见过。" } },
      { id: "yu", label: "跟郁明分一瓶汽水", next: "acad5", fx: { yu: 5 }, say: { who: "郁明", face: "rival", text: "下一篇，我们还是对手。你要是只想要一个鼓掌的人，找别人。我来，是来跟你争的。" } },
    ],
  },
  acad5: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    who: "郁明",
    face: "rival",
    lines: [
      { who: "郁明", face: "rival", voice: true, text: "一作写谁。编辑催了。催的人不管我们高一怎么争，他只管名字的顺序。" },
      { text: "顺序是一种很老的伤口。全市第一和第二，被缩进论文的第一行和第二行。缩进去之后，还是那三分的形状。" },
      { text: "他看着我，不像在让。也不像在抢。他在等我露出本来的面目。本来的面目如果是抢，他就还认得我。如果是让，他就失去一个对手，也失去一个朋友。" },
      { who: "郁明", face: "soft", text: "你要是心软，就直说。别用「你更适合」这种话来打发我。我听得懂。" },
    ],
    options: [
      { id: "a", label: "坚持写自己", next: "ch3_paper", fx: { academic: 10 }, thought: "我把名字放在第一个。他看着我，没有争。不争的那几秒，我赢了，也丢了点什么。丢掉的东西不写在论文上。" },
      { id: "b", label: "让给郁明", next: "d9", fx: { yu: 10 }, say: { who: "郁明", face: "soft", text: "……谢了。可这该是你的。你让给我的如果是愧疚，我收下会作呕。你要是真觉得这行字该我写，那我们就还是对手，只是这局你放下了。" } },
    ],
  },
  ch3_paper: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    cg: "cg_journal",
    who: "裴望",
    face: "professor",
    lines: [
      { text: "顶刊的清样摊在实验台上。我的名字印在第一行。二十岁。二十岁四个字被很多人反复说，说成一种奇迹。" },
      { text: "奇迹不提铁架床，不提母亲的折痕，不提我曾经在考场上听钟。奇迹只喜欢闭合的曲线。" },
      { who: "裴望", face: "professor", voice: true, text: "去准备颁奖。词我写好了。你照着念就行。念的时候看台下，不要看年份。" },
      { text: "我接过那一页词。词比我的人生整齐。整齐是他给我的又一份照顾。我开始分不清照顾和改写。" },
    ],
    next: "d9",
  },
  d9: {
    bg: "library",
    layer: "dream",
    bgm: "lamp",
    who: "鹿眠",
    face: "knowing",
    pose: "lean",
    lines: [
      { text: "深夜十一点。论文初稿刚写完。玻璃门外站着鹿眠。她不是学生，门禁却像认识她。" },
      { text: "她今天第三次出现在我恰好抬头的位置。恰好多了，就成了安排。安排如果来自她，我不知道该感激还是该警惕。" },
      { text: "感激是梦教我的。警惕是那张凉卡教我的。两个老师同时上课，我只能选一个先听完。" },
    ],
    options: [
      {
        id: "ask",
        label: "听她把话说完",
        next: "acad6",
        fx: { d: 6, lu: 10 },
        say: { who: "鹿眠", face: "whisper", pose: "lean", text: "你记得酒店八楼没有 301 房吧？你昨晚又拿房卡去刷了。刷的时候你很专心。专心是你的长处，也是你的病。" },
        thought: sting,
      },
      { id: "skip", label: "打断她，回去改论文", next: "acad6", thought: "我低下头。门外的人影等了一会儿，走了。走的声音很轻。轻让我愧疚。愧疚没有让我追出去。论文上还有一个逗号没放好。" },
    ],
  },
  acad6: {
    bg: "lab",
    layer: "dream",
    bgm: "lab",
    who: "裴望",
    face: "professor",
    lines: [
      { who: "裴望", face: "professor", voice: true, text: "留下读博，或者现在就出去。你自己定。自己定的意思是，两条我都给你铺过了。" },
      { text: "铺过了的路还叫自己定吗。我看着他。他眼里有期待，期待我选那条能继续让他写词的路。" },
      { text: "我不是不感恩。感恩已经多到压肩。压肩的感恩如果不能拒绝，它就从恩变成了栏杆。" },
    ],
    options: [
      { id: "a", label: "留校深造", next: "daily4", fx: { academic: 10 }, thought: "我点了头。未来被排成一张很干净的表。表上没有六月九日。没有的日子，是我用点头换掉的。" },
      { id: "b", label: "出去创业", next: "daily4", fx: { academic: -5 }, thought: "我说想试试别的。表格上的路暗了一格。他没拦。不拦的沉默里有失望。失望我也熟悉，熟悉得像家里没开灯的那个黄昏。" },
    ],
  },
  daily4: {
    bg: "lobby",
    layer: "dream",
    bgm: "cradle",
    lines: [
      { text: "梦里的最后几个傍晚，长得几乎一样。一样到我开始怀疑，成功是不是一种重复播放。" },
      { text: "我还是想见一个人。想见，是因为一样的傍晚里，只有某一个人还会说出不一样的句子。" },
      { text: "鹿眠会说电梯。沈知夏的信会自己改字。郁明会在棋盘上认输，认输的时候终于像个还没被擦掉的人。" },
    ],
    options: [
      { id: "lu", label: "在前台坐到打烊", next: "ch4", fx: { lu: 5 }, say: { who: "鹿眠", face: "knowing", text: "你坐了很久。时钟没有往前走。你注意到了，所以你还没完全住进来。住进来的人，不看钟。" } },
      { id: "shen", label: "把旧信又读一遍", next: "ch4", fx: { shen: 5 }, thought: "信上的字会动。痣那一句，时有时无。有的时候我读到她，无的时候我读到一个学姐。我把信按在桌上，按不住。" },
      { id: "yu", label: "跟郁明下完最后一盘棋", next: "ch4", fx: { yu: 5 }, say: { who: "郁明", face: "blank", text: "这盘我认输。下一盘，等你醒了再说。醒了如果还想争，我奉陪。梦里这盘不算。" } },
    ],
  },
  ch4: {
    title: "第四章 · 梦的裂缝",
    bg: "lobby",
    layer: "dream",
    bgm: "home",
    meter: true,
    fragment: "gohome",
    who: "鹿眠",
    face: "soft",
    lines: [
      { text: "鹿眠把一张房卡推过大理石台面。卡上印着 301。大理石很亮，亮得能看见我自己的下巴。", se: "card" },
      { text: "八楼没有 301。这件事我早就知道了。知道了还每天去刷，是因为刷不开的门，至少证明我还在找一个出口。" },
      { who: "鹿眠", face: "soft", voice: true, text: "睡够了，就回家。" },
      { text: "像在提醒一个忘记退房的客人。她不拉我的手。" },
      { text: "留下来很舒服。舒服是这张梦最贵的东西。" },
      { who: "鹿眠", face: "knowing", voice: true, text: "你要是还想要奖，就别接。接了，那些词就作废。疼一下。疼完你自己走。" },
    ],
    options: [
      { id: "take", label: "接过房卡", next: "ch4_door", fx: { lu: 10 }, thought: "卡是凉的。凉得像真的。真的东西不夸我。它只是凉，凉到我不得不承认手还在。" },
      { id: "push", label: "推开", next: "ch4_door", thought: "我把手收回来。她没有再推第二次。不推第二次，是她把选择留在我这边。留在我这边的东西，我反而更难假装没看见。" },
    ],
  },
  ch4_door: {
    bg: "white",
    layer: "limen",
    bgm: "white",
    meter: true,
    fragment: "heart",
    lines(state) {
      const base = [
        { text: "大厅的钟停在六月九日，六点。我听见心跳。", se: "heart" },
        { text: "梦里的我，从来不会有心跳。心跳一来，奖杯、清样、软床都轻了一寸。" },
        { text: "六月九日。母亲折成绩单的那天，我终于睡着的那天。它不是一个可以无限续住的夜晚。" },
      ];
      if (state.dissonance < WAKE_AT) {
        base.push({ text: "我去找醒来的那一项。光很平。那里没有门。平光像一张笑得很整齐的脸，不跟我吵，也不放我走。", kind: "thought" });
        base.push({ text: "留在这里，也可以叫做成功。成功如果是一扇没有把手的门，那我就还没付够那点怀疑。", kind: "thought" });
      } else {
        base.push({ text: "选项浮在白光里。门在。要不要推，是我的事。" });
        base.push({ text: "推开门不是重写昨天。昨天的三分、折痕、没说出口的话，都还在门的另一边等我。等我的不是惩罚。是一张还没被梦改过的床。" });
      }
      return base;
    },
    options(state) {
      const stay = {
        id: "stay",
        label: "留在这里——继续这场人生",
        next: state.academic >= ACADEMIC_SPLIT ? "end_b" : "end_c",
      };
      if (state.dissonance >= WAKE_AT) {
        return [{ id: "wake", label: "醒来——回到那晚", next: "finale" }, stay];
      }
      return [stay];
    },
  },
  end_b: {
    bg: "faceless",
    layer: "dream",
    bgm: "applause",
    cg: "cg_faceless",
    fragment: "faceless",
    ending: "B",
    lines: [
      { text: "颁奖台很高。高处的风不冷。台下的人没有脸。他们鼓掌，嘴巴的位置是平的。" },
      { text: "我笑着鞠躬。笑是练过的。练的时候老裴在旁边看词，郁明的生日已经被奶油糊住，沈知夏的痣不在，母亲的声音轻得刚好。" },
      { text: "奖杯很沉，沉得像一口井。我抱着它，井不说话。不说话的成功最像爱，因为它一直在，而且不要你回头看去年。" },
      { text: "有一刻我很想喊一个人的名字。喊谁都行。喊出去，台下应该有一张脸转过来。没有。掌声只是齐。" },
      { text: "完美停在这一步。我没有再醒来。也没有真正活过。活过需要一颗会疼的心跳，而心跳在很早以前就被我当成了干扰项。" },
      { text: "多年以后如果还有人提起那个最年轻的学者，他们会说他很稳。稳是真的。稳的人站在井边上，自己就是井盖。" },
    ],
  },
  end_c: {
    bg: "diary",
    layer: "dream",
    bgm: "crack",
    ending: "C",
    lines: [
      { text: "后来我结了婚。妻子很好。孩子会在晚饭前喊我。日子一天不落地圆满，圆满到连吵架都吵不长久。" },
      { text: "我做的工作受人尊敬。尊敬来的时候，我总会先说谢谢。谢谢说得很熟练，熟练得像在念别人写好的词。" },
      { text: "母亲老了，不再提家里的脸。她只问我吃不吃得惯。我吃得惯。吃得惯是一种成功。我偶尔会在咽下去的时候，想起食堂里那盘不被承认的红烧肉。" },
      { text: "很老的那个晚上，孩子睡了。我翻开日记的最后一页。字是我的。笔画像我。连停顿都像我。" },
      { text: "上面写着：这不是我的人生。" },
      { text: "我看了很久，没有生气。生气需要一个还肯怀疑的人。我只是把本子合上，关灯。黑暗里，这句话还在。它不喊我回去。它只是让这一生的圆满，在最后一页露出一道折痕。" },
    ],
  },
  finale: {
    title: "终章 · 醒来之后",
    bg: "dorm",
    layer: "real",
    bgm: "heart",
    cg: "cg_wake",
    meter: true,
    lines: [
      { text: "心跳还在。床是铁的。九十厘米。铁架响了一声，整栋楼都该听见。", se: "heart" },
      { text: "六月九日，凌晨。成绩单还在桌上，折痕还在。梦里的奖杯不在。清样不在。二十岁的奇迹不在。" },
      { text: "我坐起来。手心全是汗。汗是真的。真的东西又小又狼狈，可它不会把年份印错。" },
      { text: "我没有变成一个突然坚强的人。我只是醒了。醒了的第一件事不是立志，是摸一摸床沿，确认它还会响。" },
      { text: "响了。我居然笑了一下。笑完眼眶热。热的不是委屈。是那些被梦改掉的人，忽然又有了落回原处的可能。" },
    ],
    next: "f1",
  },
  f1: {
    bg: "home",
    layer: "real",
    bgm: "awake",
    meter: true,
    who: "裴望",
    face: "soft",
    lines: [
      { text: "天亮以后，家里还是没有把灯全打开。不同的是，母亲把一杯水放在我手边，没有把成绩单再折一次。" },
      { text: "老裴来得早。他眼睛里有血丝。血丝让我安心。梦里的他从没有血丝，梦里的他永远来得及替我写好下一场的词。" },
      { who: "裴望", face: "soft", voice: true, text: "复读的表在这儿。报名费我可以先垫。你要是觉得这又是安排，那你就自己交。我不是来收你的人生的。" },
      { text: "这句话他梦里没说过。梦里的照顾是铺路。醒着的照顾肯把路从自己手里放开。" },
      { text: "我看着那张表。表很丑，油墨不匀。丑很好。丑说明它还没被谁写成奇迹。" },
    ],
    options: [
      { id: "self", label: "自己交报名费", next: "repeat_room", thought: "我把积下来的钱数了一遍。够。数的时候手指发紧。这是我自己的一年。自己的，不是说没有人帮过我，是这笔钱的重量我认。" },
      { id: "pei", label: "接受老裴的安排", next: "repeat_room", say: { who: "裴望", face: "soft", voice: true, text: "行。你只管把觉睡回来。觉回来了，字才会端正。端正这件事，我们再练一年。" } },
    ],
  },
  repeat_room: {
    bg: "repeat",
    layer: "real",
    bgm: "awake",
    cg: "cg_repeat",
    meter: true,
    who: "裴望",
    face: "stern",
    lines: [
      { text: "复读班的教室比去年更挤。黑板上的倒计时从三百多天开始。粉笔灰落在第一排的桌上，没有人觉得这是耻辱的灰尘。" },
      { text: "有人比我大两岁。有人眼睛更红。没有人问我是不是那个全市第二。第二在这里不是勋章，也不是伤口的展示牌。它只是你来过的证明。" },
      { who: "裴望", face: "stern", voice: true, text: "坐后面。别挑灯光好的位置。灯光好，人就容易又去演一个好学生。" },
      { text: "我把铁架床的声音留在去年。这张桌子是醒着的。醒着的桌子上，我会把字写坏，再写一遍。写坏不再等于我家的脸掉在地上。" },
      { text: "母亲那天没有送到门口。她说家里的菜还在锅里。锅里的菜比送行真实。我走的时候没有回头演一场告别。" },
    ],
    next: "f2",
  },
  f2: {
    bg: "dorm",
    layer: "real",
    bgm: "awake",
    meter: true,
    lines: [
      { text: "复读第一夜。床还是窄，窄得诚实。我看着闹钟，不知道该把它定在哪一刻。" },
      { text: "定得太远，像跟一年后的自己许诺。许诺是梦喜欢的东西。定得太近，又像我只敢活到明天早上。" },
      { text: "上铺的人已经睡着了。鼾声很普通。普通让我眼眶一热。我没有把这热当成感悟。我只是把闹钟拿在手里，听它不响。" },
    ],
    options: [
      {
        id: "alarm",
        label: "设成六月九日，六点",
        next: "f3",
        fragment: "alarm",
        thought: { text: "梦醒的那一天，我把它改成出发的那一天。不是纪念失败。是让那个曾经只用来睡着的凌晨，改成我肯起床的凌晨。", se: "alarm" },
      },
      { id: "morning", label: "设成明天早上六点", next: "f3", thought: "明天先到。六月九日会自己来。它来的时候，我如果还醒着，就够了。不必先把它刻成一个节日。" },
    ],
  },
  f3: {
    bg: "corridor",
    layer: "real",
    bgm: "awake",
    meter: true,
    who: "裴望",
    face: "soft",
    lines: [
      { text: "一年里我睡过好觉，也睡错过。字端正过，也飘过。飘的那天我没有去听钟。我把笔握紧，写完那个发虚的句子。" },
      { who: "裴望", face: "soft", voice: true, text: "二考前夜，学校还是订了酒店。眠夏。去不去，你定。这次我把「我知道你失眠」这句话咽回去。你自己比我清楚。" },
      { text: "他咽回去的那句，是把我从他的学生这个身份里放出来一寸。一寸就够我决定。决定不再是拒绝恩典，也不再是接受安排。" },
    ],
    options: [
      { id: "hotel", label: "去眠夏酒店住一晚", next: "fin_hotel", fx: { lu: 10 } },
      { id: "home", label: "住在家里", next: "fin_home" },
    ],
  },
  fin_hotel: {
    bg: "lobby",
    layer: "real",
    bgm: "awake",
    meter: true,
    fragment: "milk",
    who: "鹿眠",
    face: "smile",
    lines: [
      { text: "前台抬起头。是她。这次我记住了。不是梦补完的那张脸，是一个会在夜班里打哈欠、又把哈欠咽回去的人。" },
      { text: "白衬衫的袖口有一点洗旧。洗旧很好。梦里的白衬衫永远是新的。" },
      { who: "鹿眠", face: "smile", voice: true, text: "热牛奶。高考那两天我也递过。你没接住。不是你的错，那时候你的手里只有准考证。" },
      { text: "牛奶上结了一层薄皮。我看着那层皮，没有立刻把它当成象征。它就是皮。我把它吹开，喝了一口。烫。" },
      { who: "鹿眠", face: "knowing", text: "八楼有房间。房间号是印得出来的那种。你要是再刷出一面平墙，就下来找我。这次我会说，你看错了，而不是说你不够努力。" },
      { text: "我点头。点头不再是今天唯一会做的事。我还可以把杯子放下，还可以问她叫什么。问之前我已经知道答案。知道和听见，不是同一件事。" },
    ],
    options(state) {
      if (!hiddenReady(state)) return [];
      return [
        { id: "hidden", label: "我们是不是见过", next: "end_e" },
        { id: "staynight", label: "我是来住一晚的", next: "second_exam" },
      ];
    },
    next(state) {
      return hiddenReady(state) ? null : "second_exam";
    },
  },
  fin_home: {
    bg: "home",
    layer: "real",
    bgm: "awake",
    meter: true,
    who: "黍母",
    face: "warm",
    lines: [
      { text: "我住在家里。厨房的灯开着。灯不是为了迎接一个考生，是粥要看火。" },
      { text: "母亲把切好的水果推过来，没再提名次。水果切得大小不一。大小不一让我鼻子一酸。梦里的她不会切出这种笨拙。" },
      { who: "黍母", face: "warm", voice: true, text: "早点睡。明天我叫你。叫你的时候要是你烦，就烦。别再把我一句话背一整年。" },
      { text: "她知道。她知道那句关于脸的话被我背熟了。知道了不解释，只把以后的早晨许给我。解释会变成另一场辩论。早晨只是早晨。" },
      { text: "她的声音有一点哑。不再温柔得像一句录音。哑是熬夜留下的。熬夜的母亲比会做一切菜的母亲更让我想留下来。" },
      { text: "我没说对不起。对不起太像梦里的词。我把碗洗了。洗的时候她在旁边看了一会儿，说行了，去睡。去睡两个字，比任何奖状都沉。" },
    ],
    next: "second_exam",
  },
  second_exam: {
    bg: "examout",
    layer: "real",
    bgm: "awake",
    cg: "cg_outside",
    meter: true,
    lines: [
      { text: "二考那天，考场外的风是热的。我睡过了。睡过不是奇迹，是这一年里我终于肯把闹钟当成闹钟，而不是当成审判。" },
      { text: "笔还是会抖一下。抖一下我就停，再写。不停下来跟自己打架。" },
      { text: "门开着。这次不是梦里的白光。门里有汗味，有翻卷子的声音，有人咳嗽。咳嗽很好。咳嗽的人有喉咙。" },
      { text: "我走进去的时候没有跟自己说一定要成功。一定要，是梦的句法。我只说：把这张卷子写完。写完之后，无论数字是什么，我都还在这个热的风里。" },
    ],
    next: epilogueId,
  },
  epi_lu: {
    bg: "gate",
    layer: "real",
    bgm: "awake",
    cg: "cg_reunion",
    ending: "TRUE",
    who: "鹿眠",
    face: "smile",
    lines: [
      { text: "复读的一年很长。长不是因为苦。苦我早就认识。长是因为每一天都有具体的重量，不能用一张软床买掉。" },
      { who: "鹿眠", face: "smile", voice: true, text: "这次醒着考。我在门口。不在你的成功里面，在门口。你要是过了线，我也还是在门口。别把我写进通知书。" },
      { text: "一年后，秦华的校门没有多出来的笔画。石头是旧的，旧得有手摸过。她把热牛奶放进我手里。皮还是那层皮。我吹开，喝了。" },
      { text: "我没有重写昨天。昨天的三分还在，母亲的折痕还在，我拒绝过的那张酒店床也还在。我只是来到了明天。明天不负责把我变成一个没有亏欠的人。" },
      { text: "她下班的时间跟我的课不齐。不齐也好。齐了又会像梦。我们约在校门口见面的时候，常常有一个要等。等的人会看树。树不会停在六月九日。" },
    ],
  },
  epi_shen: {
    bg: "classroom",
    layer: "real",
    bgm: "awake",
    cg: "cg_reunion",
    ending: "TRUE",
    who: "沈知夏",
    face: "smile",
    lines: [
      { text: "复读的一年里，我把那张折着的纸读了很多遍。读到后来，纸软了。软了的纸还是那一句：别只看着名次。" },
      { text: "我给她写过信。信写得很笨。笨在我终于不用第二名当开头。开头是天气，是食堂的菜，是我今天没有把谁当成对手。" },
      { who: "沈知夏", face: "smile", voice: true, text: "通知书到了？右眼角……你还在看。看就看。这次别假装看黑板。" },
      { text: "痣还在。没有被改写成一个更适合成功故事的学姐。她还是那个会先把退路递给我的人。我这次没有把退路收进口袋。" },
      { text: "我没有重写昨天。昨天我让她的目光在我肩上停过，又移开。那一下移开，我还欠着。欠着也可以走路。走路的时候我看着她，不是看着名次。" },
      { who: "沈知夏", face: "quiet", voice: true, text: "够了。不是原谅你。是我也不想再当一张你不敢拆的纸。" },
    ],
  },
  epi_yu: {
    bg: "home",
    layer: "real",
    bgm: "awake",
    cg: "cg_reunion",
    ending: "TRUE",
    who: "郁明",
    face: "bright",
    lines: [
      { who: "郁明", face: "bright", voice: true, text: "笔记我寄来了。生日我也想起来了。是三月。你要是再问我大概，我就真跟你翻脸。" },
      { text: "我笑了一下。梦里的他记不住的东西，醒着的他都在。在，不是因为他完美。是因为没有人用奶油把他糊住。" },
      { text: "我们还是会争。争一道题的时候，他不再先把台阶递过来让我下不来台。我也不再把输赢听成我这个人短了三寸。三寸还在。三寸只是三寸。" },
      { who: "郁明", face: "rival", voice: true, text: "秦华要是我们都在，你别让着我。让着我的那种谢，我消化不了。" },
      { text: "通知书很薄。我把它和那叠笔记放在一起。薄的纸和厚的笔记压在桌上，谁也不必变成谁的奖杯。" },
      { text: "明天从这里开始。开始的意思不是我们终于成为彼此的光。是我们可以在同一张桌子上把字写坏，再写好，写好了也不必鞠躬。" },
    ],
  },
  epi_default: {
    bg: "exam",
    layer: "real",
    bgm: "awake",
    cg: "cg_reunion",
    ending: "TRUE",
    lines: [
      { text: "复读的一年很长。没有人替我醒来。是我自己按掉闹钟，走进考场。走进去的时候腿是软的。软也走完了。" },
      { text: "秦华的通知书很薄。够用了。够用不是圆满。圆满是梦里那种一天不落的日子。够用是我还能用这张薄纸去换一间真实的宿舍，一张会响的床。" },
      { text: "我没有重写昨天。昨天的失败还坐在家里的抽屉最底下。我只是愿意醒来，然后重考一次。重考不是洗掉三分。是承认三分之后，手还肯拿笔。" },
      { text: "出分那天我给母亲打了电话。她沉默了两秒，说吃饭吧。吃饭吧这三个字，比恭喜更像她。我在电话这头笑了一下，没让她听见。" },
    ],
  },
  epi_tie: {
    bg: "gate",
    layer: "real",
    bgm: "awake",
    cg: "cg_reunion",
    ending: "TRUE",
    lines: [
      { text: "考完那天，不止一个人在校门口等我。等的方式都不一样。鹿眠靠着门柱，牛奶凉了一点。沈知夏把一封新的信捏出了折。郁明站得远一点，像还在给所有人让出半步。" },
      { text: "热牛奶、一封旧信、一叠笔记，叠在一起。我谁也没有放下。放下任何一个，都会把剩下的人写成配角。他们不是我的成功的配角。" },
      { text: "老裴没有来。他发了一条很短的消息：字端正了就行。我回：端正了。回完才发觉，我终于不是在向他交一份人生。" },
      { text: "明天不只有一条路。可它是醒着的。醒着的路上，人会迟到，会说错话，会把爱表达得很笨。笨比梦里的刚好，更值得走过去。" },
    ],
  },
  end_e: {
    bg: "white",
    layer: "limen",
    bgm: "together",
    ending: "E",
    who: "鹿眠",
    face: "smile",
    lines: [
      { text: "我看着她。牛奶还是热的。热气碰到白光，散得很慢。" },
      { text: "这一年我醒过，也怀疑过自己是不是只是醒在另一层更精致的梦里。精致的标志是：一切都刚好能解释。" },
      { who: "黍琊", face: "awake", voice: false, text: "如果这也是梦呢。" },
      { who: "鹿眠", face: "smile", voice: true, text: "那我们一起醒。不是我拉你。你要是再看见平墙，别一个人刷到天亮。" },
      { text: "钟走到了六月十日。十日没有奇迹。她的袖口还是旧的。我的手心还有一点汗。", se: "clock" },
      { text: "汗和旧袖口都留了下来。这一次，光没有把我们改干净。" },
    ],
  },
};
